---
title: Volcomism Rants
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
webrick:
  headers:
    what-header: rawr
email: anthony.a.moreno@gmail.com
description: 'A simple space for me to rant about nothings and everythings.

'
baseurl: ''
url: http://volcomism.github.io
twitter_username: rawrthis
github_username: volcomism
markdown: kramdown
gems:
- jekyll-gist
- jekyll-mentions
